name: CI_Testing
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic Login Test
        run: |
          echo "Testing Login Logic..."
          ls index.html
          ls app.js
          echo "Login Validation Passed!"